spring.application.name=dvd-rental-api

spring.datasource.url=jdbc:postgresql://localhost:5432/dvd_rental
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

cors.allowed-origins=http://localhost:4200